### PR TITLE
avoid question and display waiting message when running mdadm

### PR DESCRIPTION
**Pull request by nraynaud**

### CODE REVIEW

**Review by stormi — COMMENTED** [review]
Can you re-do the commit without the trailing space changes? They will probably cause conflicts in the future when we merge changes from upstream. (amending the commit + force pushing the branch would be ideal)

**Comment by nraynaud** [comment]
the struggle is real

**Comment by nraynaud** [comment]
I think I got it?

**Comment by stormi** [comment]
yes ! :)

**Pull request merged**
